### ISSUE TITLE
Allow to specify ordering by multiple criteria with OOP

### ISSUE THREAD

**Issue by TrangOul** [pkozuchowski/Apex-Opensource-Library#5]
Suppose I want the following query:

```sql
SELECT Id
FROM Account
ORDER BY Name, OwnerId
```

I cannot do the following:

```apex
Query.Accounts
	.orderBy(Account.Name.getDescribe().getName())
	.orderBy(Account.OwnerId.getDescribe().getName())
	.getList();
```

since only the last `orderBy` will be applied - `QueryBuilder` stores only a single condition and immediately prepends it with `ORDER BY` (`setOrderBy`), and setting it again overwrites the previous condition.
The resulting query has only one ordering:

```sql
ORDER BY OwnerId
```

To get the desired result, I have to specify the ordering by an ugly hardcoded String:

```apex
Query.Accounts
	.orderBy('Name, OwnerId')
	.getList();
```

Or, if I want to follow the best practices and use `SObjectField`s to track the field usage:
```apex
Query.Accounts
	.orderBy(Account.Name.getDescribe().getName() + ',' + Account.OwnerId.getDescribe().getName())
	.getList();
```

This would get even messier if I wanted to specify the direction (`ASC`/`DESC`) or nulls (`NULLS` `LAST`/`FIRST`).

Please make it possible to specify ordering in the OOP way.
Please also make it possible to specify the fields by `SObjectField` instead of a `String` (not only in ordering). For example `QueryBuilder` offers functions `addField(SObjectField)` and `addField(List<SObjectField>)`, but they are not present in `QueryObject`.

**Comment by pkozuchowski** [comment]
Hey, thanks for feedback.

Let me correct one things first before I get to main topic:
`Account.Name.getDescribe().getName()` is very often used by devs, but it's not a good practice actually, because it unnecessarily calls description method, which is costly and long to write.  
SOBjectField token is an API name itself and doesn't require additional description call. If you want to get API name as string, you have 3 simpler and much more performant alternatives:

1. `'' + Account.Name;`
2. `Account.Name.toString();`
3. `String.valueOf(Account.Name);`


**On the topic:**
Using strings instead of SObjectFields as primary field source for the framework is a Key Design Decision that I took deliberately using following arguments:
1. It's trivial to turn SObjectFields into Strings, by using one of the above methods. However, turning string into SObjectField requires costly sObject description calls and a lot of overhead code. This asymmetry not just favors, but simply dictates String as a baseline parameter type - if you have class that supports both, your field list will be `List<String>`.
3. Queries involve a lot of cross-object relationship fields, which are not supported by SObjectField in any way and will not be protected from changing relationship name.
4. Some of the query parameters are not fields at all - `COUNT(), FORMAT()`, etc
5. Supporting both strings and tokens increases method count (well it's not too bad tbh, now that I've counted which methods would make sense)
6. Using tokens, make certain SOQL syntax combinations incredibly complicated, where the framework should be as easy to use on client side as possible.

To sum up, String has to be the main parameter type, but it wouldn't hurt to provide token support for commonly used methods.


**On the ORDER BY topic** 
Given above KDD, it is actually expected to call the method with `orderBy('Name, OwnerId')` as equivalent of the SOQL's `ORDER BY Name, OwnerId`. The difficulty as you noticed, is making reasonable interface for tokens, that would work with ASC/DES and NULLS Last/FIRST - any implementation will be just much more messy than a string. While it's true, that string doesn't make it safe on compile as token do.

I didn't think of calling orderBy() a few times, it simplifies the interface issue, if we call it as bellow and is easy to implement:
```java
.orderBy(Account.Name, true, true)
.orderBy(Account.OwnerId, true, true)
```
But after thinking a while, I see 2 issues:

1. It may be a bit counter-intuitive, since SOQL doesn't expect ORDER BY to appear twice
2. If you define query object to have default `orderBy()`, you can't actually overwrite this anymore
```java
    public AccountQuery() {
        super(new List<String>{
            '' + Account.Id,
            '' + Account.Name
        }, Account.SObjectType);
        this.orderBy(Account.Name, true, true);
    }
````

It's a borderline scenario, so considering pros/cons, I think it's sensible approach.

Alternatively, OOP interface could look like one of those:
```java
Query.Accounts
    .with(Query.orderBy(Account.Name, true, false))
    .with(Query.orderBy(Account.OwnerId)))
    .getList();

Query.Accounts
    .with(Query
        .orderBy(Account.Name, true, false)
        .orderBy(Account.OwnerId))
    .getList();

// With or without Query namespace
Query.Accounts
    .with(new Query.OrderBy(Account.Name, true, false))
    .with(new Query.OrderBy(Account.OwnerId))
    .getList();

Query.Accounts
    .with(new Query.OrderBy(Account.Name).ascending().nullsFirst())
    .with(new Query.OrderBy(Account.OwnerId))
    .getList();
```

**Comment by pkozuchowski** [comment]
I have the changes done, will publish it after my work today

**Comment by pkozuchowski** [comment]
@TrangOul  Pushed the update, if there's anything more needed, feel free to reopen :)

**Comment by TrangOul** [comment]
Looks good, thank you for quick update!
Thank you also for putting the explanation in the docs. More important to know _how_ it is done (which can be easily checked in the source code) is _why_.
